sudo: required
services:
  - docker
  
before_install:
  - docker build -t thanap/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run thanap/react-test npm test -- --coverage

after_success:
  - docker build -t thanap/multi-client ./client
  - docker build -t thanap/multi-nginx ./nginx
  - docker build -t thanap/multi-server ./server
  - docker build -t thanap/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password--stdin
  
  # Take those images and push to docker hub
  - docker push thanap/multi-client
  - docker push thanap/multi-nginx
  - docker push thanap/multi-server
  - docker push thanap/multi-worker
  
   
 

